name: WPCS check

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
  phpcs:
      name: WPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: WPCS check
          uses: 10up/wpcs-action@stable
